spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL_MYSQL}
    username: zuper
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/auth/realms/proposal-realm}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:18080/auth/realms/proposal-realm/protocol/openid-connect/certs}

  jpa:
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,prometheus
        exclude: env,beans
    prometheus:
      enabled: true
api:
  jaeger:
    host: ${JAEGER}
  data-analysis:
    host: ${ANALISE}
    url: ${api.data-analysis.host}:9999
  account:
    host: ${CONTAS}
    url: ${api.account.host}:8888
    scheduled-time: 60000

feign:
  circuitbreaker:
    enabled: true

opentracing:
  jaeger:
    enabled: true
    service-name: ${spring.application.name}
    http-sender:
      url: ${api.jaeger.host}:14268/api/traces
    probabilistic-sampler:
      sampling-rate: 1
