spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:proposal-database-test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

api:
  data-analysis:
    host: localhost
    url: ${api.data-analysis.host}:9999
  account:
    host: localhost
    url: ${api.account.host}:8888
    scheduled-time: 5000

feign:
  circuitbreaker:
    enabled: true

opentracing:
  jaeger:
    enabled: false
